# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: v$NEXT_PATCH_VERSION 🌈
tag-template: v$NEXT_PATCH_VERSION
version-template: $MAJOR.$MINOR.$PATCH
no-changes-template: No Changes
branches:
  - master
# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 🚨 Removed
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  # Various tags are used in the repositories, https://github.com/toolmantim/release-drafter/issues/218
  - title: 🚀 New features and improvements
    label: enhancement
  - title: 🚀 New features and improvements
    label: feature
  # Various tags are used in the repositories, https://github.com/toolmantim/release-drafter/issues/218
  - title: 🐛 Bug Fixes
    label: bug
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🐛 Bug Fixes
    label: bugfix
  - title: 🐛 Bug Fixes
    label: regression
  - title: 📖 Documentation updates
    label: documentation
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    label: dependencies
  - title: 📦 Dependency updates
    label: deps
  - title: 📦 Dependency updates
    label: dependabot
  - title: 👻 Maintenance
    label: chore
  # TODO: consider merging category or changing emojis
  - title: 🚦 Internal changes
    label: internal
  - title: 🚦 Tests
    label: test
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changelog

  $CHANGES

  A big thanks to:

  $CONTRIBUTORS
